### ISSUE TITLE
Add Coins & Sound!

### ISSUE THREAD

**Issue by Xevion** [n0remac/2020GameJamPractice#8]
Step 6 must be implemented: [**Add Coins & Sound!**](https://arcade.academy/examples/platform_tutorial/index.html#step-6-add-coins-and-sound)

**Comment by Xevion** [comment]
Since sounds weren't added, I don't know whether or not keeping this issue closed is a good idea.  _Reopen?_

**Comment by n0remac** [comment]
Let's keep it closed and I'll create a new card.
